name: "Checks"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Setup Task
        uses: arduino/setup-task@accf38bba955639d21816bb68775e5c48c482182
      - name: "Read Python Version"
        id: read-python-version
        uses: pCYSl5EDgo/cat@264f5b318158276af69bd0a2a9f1e613b2d03ebf
        with:
          path: ./.python-version
          trim: true
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ steps.read-python-version.outputs.text }}"
      - name: "Cache Base Dependencies"
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip/
          key: pip-${{ runner.os }}-${{ hashFiles('./.python-version', './base-dependencies.txt') }}
      - name: "Install Base Dependencies"
        run: python3 -m pip install --requirement ./base-dependencies.txt
      - name: "Cache Package Dependencies"
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs/
          key: poetry-${{ runner.os }}-${{ hashFiles('./.python-version', './poetry.lock') }}
      - name: "Run"
        run: task ci
